# Generated by Django 4.2.4 on 2023-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=18)),
                ('email', models.EmailField(max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
    ]
